---
abstract: 'Utility functions for REST applications'
author:
  - 'Jaldhar H. Vyas <jaldhar@braincells.com>'
build_requires:
  Test::More: 0
  Test::WWW::Mechanize::CGI: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: REST-Utils
provides:
  REST::Utils:
    file: lib/REST/Utils.pm
    version: 0.2
requires:
  perl: 5.008
resources:
  homepage: http://jaldhar.github.com/REST-Utils
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jaldhar/REST-Utils
version: 0.2
